# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation
# Still in development, subject to change without notice!!

language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=NON_OMV_TESTS

install: 
    - cd
    
    # Install OMV (needed for testing onluy, not running model)
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

    # Install python dependencies using setup.py

    - cd $TRAVIS_BUILD_DIR
    - pwd
    - ls
    - python setup.py install

script:

    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."


    # Test analysis of channels using pynml-channelanalysis from PyNeuroML
    
    - cd ./NeuroML2/
    - pynml-channelanalysis -temperature 34  -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev 50  -nogui  ./ca_boyle.channel.nml
    - pynml-channelanalysis -temperature 34  -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev -55 -nogui  ./k_fast.channel.nml
    - pynml-channelanalysis -temperature 34  -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev -55 -nogui  ./k_slow.channel.nml
    
    
    # Test generation of iv curve for ca channel
    
    - ./ivcurve_ca_boyle.sh -nogui
    
    
    # Test Python version of Boyle & Cohen model
    
    - cd ../BoyleCohen2008/PythonSupport/Main_Version
    - python vclamp.py -nogui
    - python vclamp_decimal.py -nogui
    - python compareToNeuroML2.py

    
    
